[package]
edition = "2021"
name = "migration"
publish = false
version = "0.1.0"

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
chrono = "0.4.19"
entity = { path = "../entity" }
sea-orm-migration = { version = "0.8.2", default-features = false }
